# Nom du workflow
name: "Déploiement auto suite à un push"

# Déclencheur 
on:  
  push: 
    branches: 
      - main

# -----------------------------------------------------

jobs:
  deploy:
    name: "Déploiement sur le serveur"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configuration SSH
        env: 
          SSH_KEY: ${{secrets.SSH_KEY}}
          SSH_USER: ${{secrets.SSH_USER}}
        run: |
          # Création du dossier SSH
          mkdir -p ~/.ssh
          
          # Écriture de la clé privée
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          # Configuration SSH avec l'IP et le port spécifiques
          echo -e "Host deploy_host\n\
            HostName 172.16.199.254\n\
            User $SSH_USER\n\
            Port 22\n\
            IdentityFile ~/.ssh/deploy_key\n\
            StrictHostKeyChecking no\n\
            LogLevel DEBUG3" > ~/.ssh/config

      - name: Test de connexion SSH
        run: |
          # Test de connexion SSH avec verbosité
          ssh -v deploy_host 'echo "Test de connexion réussi"'

      - name: Déploiement via SSH
        run: |
          # Synchronisation des fichiers avec plus de verbosité
          rsync -avvz --delete \
            --exclude '.git*' \
            --exclude 'node_modules' \
            --timeout=60 \
            -e "ssh -p 22" \
            ./ deploy_host:/var/www/pokedex/ || {
              echo "Erreur lors de la synchronisation rsync"
              exit 1
            }

          # Connexion SSH et redémarrage des services avec gestion d'erreurs
          ssh deploy_host '
            cd /var/www/pokedex && \
            docker-compose down && \
            docker-compose up -d --build
          ' || {
            echo "Erreur lors du redémarrage des services Docker"
            exit 1
          }
